version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: suraj
      POSTGRES_DB: postgres

    ports:
      - 5433:5432
